name: Analytrix Daily Reminder

on:
  schedule:
    # 9:00 AM IST = 3:30 AM UTC
    - cron: "30 3 * * *"

  # Manual testing
  workflow_dispatch:

jobs:
  daily-reminder:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Send Analytrix Morning Emails
        env:
          GMAIL_USERNAME: ${{ secrets.GMAIL_USERNAME }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}

        run: |
          python scripts/daily_reminder.py
